import me.jameshunt.inmotiontestapplication.colors.Color

@startuml

ShowColors: val data: List<Color>
ColorSelected: val data: Color

[*] -> GatherData
GatherData --> ShowColors
ShowColors --> ColorSelected
ShowColors --> GatherData
ShowColors --> Back
ColorSelected --> GatherData

@enduml