import me.jameshunt.business.Profile

@startuml

SaveProfile : val formData: Profile

Done : val formData: Profile

[*] -> GetProfile
GetProfile --> ProfileRequest
ProfileRequest --> SaveProfile
SaveProfile --> Done
GetProfile --> Done

@enduml