@startuml

[*] -> LoginForm

CheckCredentials : val formData: me.jameshunt.inmotiontestapplication.login.LoginFragment.LoginFormData

LoginForm ---> CheckCredentials
LoginForm --> Back

CheckCredentials --> GetProfile
CheckCredentials --> ShowError

ShowError --> LoginForm

GetProfile --> Done
GetProfile --> ShowError

@enduml