import me.jameshunt.inmotiontestapplication.login.LoginFragment.LoginFormData

@startuml

[*] -> LoginForm

CheckCredentials : val formData: LoginFormData

LoginForm ---> CheckCredentials
LoginForm --> Back

CheckCredentials --> GetProfile
CheckCredentials --> ShowError

ShowError --> LoginForm

GetProfile --> Done
GetProfile --> Back

@enduml